services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: order-management-api
    ports:
      - "3000:3000"
    environment:
      - ENTITY1_BASE_URL=http://host.docker.internal:7777
      - MONGO_URI=mongodb://mongo:27017/order_management
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mongo_data:
